version: '3'

services:
  web:
    image: python:3.12
    container_name: django_app
    env_file: 
      - .env/.local  # Load environment variables from .env file
    volumes:
      - ./:/usr/src/app  # Mount the current directory to the app directory in the container
    ports:
      - "8000:8000"  # Map port 8000 on the host to port 8000 in the container
    working_dir: /usr/src/app  # Set the working directory inside the container
    depends_on:
      - redis  # Ensure Redis service starts before Django
    networks:
      - django_network

  redis:
    image: "redis:alpine"
    container_name: redis_server
    ports:
      - "6379:6379"  # Expose Redis on port 6379
    networks:
      - django_network

networks:
  django_network:
    driver: bridge  # Use the bridge network driver
