version: '3.8'

services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "8000:8000" # Django
    volumes:
      - ./social_media_api:/app/django
    # environment:
    #   - DJANGO_SETTINGS_MODULE=social_media_api.settings
    command: ["/app/entrypoint.sh"]
