# Generated by Django 5.1.1 on 2024-09-24 16:23

import django.db.models.deletion
import social_media_api.chat.models
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="GroupsManage",
            fields=[
                ("name", models.CharField(max_length=50)),
                (
                    "groupID",
                    models.CharField(
                        default=social_media_api.chat.models.GroupsManage.generate_uuid,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                        unique=True,
                    ),
                ),
                (
                    "owner",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
        ),
    ]
