# Generated by Django 5.1.1 on 2024-09-26 09:17

import social_media_api.chat.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("chat", "0001_initial"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="messagegroup",
            name="id",
        ),
        migrations.AddField(
            model_name="messagegroup",
            name="groupID",
            field=models.CharField(
                default=social_media_api.chat.models.generate_uuid,
                editable=False,
                primary_key=True,
                serialize=False,
                unique=True,
            ),
        ),
    ]
