# Generated by Django 5.0.6 on 2024-12-26 10:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0002_alter_posts_id'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='posts',
            name='reactions_count',
        ),
        migrations.AddField(
            model_name='posts',
            name='likes_count',
            field=models.IntegerField(default=0, verbose_name='likes count'),
        ),
    ]
