# Generated by Django 5.0.6 on 2024-12-26 12:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0003_remove_posts_reactions_count_posts_likes_count'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='posts',
            name='likes_count',
        ),
    ]
