# Generated by Django 5.1.1 on 2024-09-17 07:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("posts", "0003_alter_posts_image"),
    ]

    operations = [
        migrations.AlterField(
            model_name="posts",
            name="updated_at",
            field=models.DateTimeField(auto_now=True, verbose_name="updated at"),
        ),
    ]
