# Generated by Django 5.1.1 on 2024-09-17 12:54

from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("posts", "0007_remove_posts_comments_count"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name="reaction",
            unique_together={("post", "author")},
        ),
    ]
