# Generated by Django 5.1.1 on 2024-09-22 10:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("friendship", "0003_alter_myfriends_me"),
    ]

    operations = [
        migrations.RenameField(
            model_name="myfriends",
            old_name="myFriends",
            new_name="myFriend",
        ),
    ]
