# Generated by Django 5.1.1 on 2024-09-22 10:38

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("friendship", "0004_rename_myfriends_myfriends_myfriend"),
    ]

    operations = [
        migrations.AddField(
            model_name="myfriends",
            name="created_at",
            field=models.DateTimeField(
                auto_now_add=True, default=django.utils.timezone.now
            ),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="myfriends",
            name="updated_at",
            field=models.DateTimeField(auto_now=True),
        ),
    ]
