# Generated by Django 5.1.1 on 2024-09-23 08:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("friendship", "0005_myfriends_created_at_myfriends_updated_at"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="myfriends",
            name="updated_at",
        ),
    ]
